name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_introduction: yes
